#!/bin/sh /etc/rc.common

START=99
START=99
USE_PROCD=1

start_service() {
	local enabled=$(uci get apman.main.enabled)
	if [ -z "$enabled" ] || [ "$enabled" == "0" ]; then
		return 0
	fi
	procd_open_instance
	procd_set_param command \
		/usr/bin/apman-status
	procd_set_param respawn 3600 10 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
