#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1

start_daemon() {
	local cfg="$1"

	config_get_bool disabled "$cfg" disabled 0
	[ "$disabled" -eq 1 ] && return

	local server
	config_get server "$cfg" server ""
	[ -z "$server" ] && return

	local port
	config_get port "$cfg" port "1704"

	local device
	config_get device "$cfg" device ""

	local latency
	config_get latency "$cfg" latency "0"

	local hostid=$(cat /proc/sys/kernel/hostname)	
	local instance="$hostid:$cfg"
	
	[ "$latency" -gt 0 ] && latency="--latency $latency"
	[ "$port" -gt 0 ] && port="--port $port"
	[ -n "$device" ] && device="--soundcard $device"
	[ -n "$hostid" ] && hostid="--hostID $hostid"
	[ -n "$instance" ] && instance="--instance $instance"

	procd_open_instance
	procd_set_param command \
		/usr/bin/snapclient \
		--logsink stdout \
		--logfilter '*:info' \
		--host "$server" \
		$latency \
		$port \
		$device \
		$hostid \
		$instance
	procd_set_param respawn 3600 10 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	local script=$(readlink "$initscript")
	local name=$(basename ${script:-$initscript})

	procd_open_trigger
	procd_add_config_trigger "config.change" "homesync" /etc/init.d/$name reload
	procd_close_trigger
}

start_service() {
	/etc/init.d/homesync enabled || /etc/init.d/homesync disable
	config_load homesync
	config_foreach start_daemon instance
}
